/* Generated by tools/gen-gcc.js from isa/fructus.toml - do not edit.

   The constants each immediate form of the ISA can carry.  The port
   consults these to decide which constants an instruction may be printed
   with; gas then picks the form.  */

#ifndef GCC_FRUCTUS_ISA_H
#define GCC_FRUCTUS_ISA_H

#define FRUCTUS_IMM5_BITS  5
#define FRUCTUS_IMM10_BITS 10
#define FRUCTUS_OFF8_BITS  8

static const int fructus_imm3[8] = {
  -1, 0, 1, 2, 3, 4, 6, 8
};

static const int fructus_shift3[8] = {
  15, 0, 1, 2, 3, 4, 6, 8
};

static const int fructus_immbit5[32] = {
  0x0001, 0x0002, 0x0004, 0x0008, 0x0010, 0x0020, 0x0040, 0x0080,
  0x0100, 0x0200, 0x0400, 0x0800, 0x1000, 0x2000, 0x4000, 0x8000,
  0xfffe, 0xfffd, 0xfffb, 0xfff7, 0xffef, 0xffdf, 0xffbf, 0xff7f,
  0xfeff, 0xfdff, 0xfbff, 0xf7ff, 0xefff, 0xdfff, 0xbfff, 0x7fff
};

static const int fructus_immask5[32] = {
  0xc000, 0x3000, 0x0c00, 0x0300, 0x00c0, 0x0030, 0x000c, 0x0003,
  0xf000, 0x0f00, 0x00f0, 0x000f, 0xff00, 0xf0f0, 0xcccc, 0xaaaa,
  0x3fff, 0xcfff, 0xf3ff, 0xfcff, 0xff3f, 0xffcf, 0xfff3, 0xfffc,
  0x0fff, 0xf0ff, 0xff0f, 0xfff0, 0x00ff, 0x0f0f, 0x3333, 0x5555
};

struct fructus_condimm { const char *cond; int imm; };

static const struct fructus_condimm fructus_condimm5[32] = {
  { "eq", 0 },
  { "ne", 0 },
  { "lt", 0 },
  { "ge", 0 },
  { "eq", 1 },
  { "ne", 1 },
  { "lt", 1 },
  { "ge", 1 },
  { "eq", -1 },
  { "ne", -1 },
  { "lt", -1 },
  { "ge", -1 },
  { "eq", 2 },
  { "ne", 2 },
  { "lt", 2 },
  { "ge", 2 },
  { "lt", 4 },
  { "ge", 8 },
  { "ge", 32767 },
  { "ge", 32766 },
  { "lt", -32767 },
  { "lt", -32766 },
  { "lo", 2 },
  { "hs", 2 },
  { "hs", 3 },
  { "lo", 4 },
  { "hs", 4 },
  { "lo", 6 },
  { "lo", 8 },
  { "hs", 8 },
  { "lo", 256 },
  { "hs", 256 }
};

#endif /* GCC_FRUCTUS_ISA_H */
